---
- summary:
    Успешная регистрация пользователя в системе
  status: pass

- summary:
    Проверка авторизации пользователя с существующим логином и паролем
  status: pass
  
- summary: 
    Проверка регистрации пользователя с неверным паролем
  status: pass
  
- summary:
    Проверка авторизации с помощью Githab
  status: pass

- summary:
    Проверка возможности изменения профиля
  status: pass

- summary:
    Проверка возможности ознакомиться с рейтингом пользователей
  status: pass

- summary:
    Проверка возможности просмотра рейтинга пользователей по категориям: weekly, monthly, total
  status: pass

- summary:
    Проверка возможности поиска игрока в рейтинге пользователей с помощью поисковой строки
  status: fail

- summary:
    Проверка работы фильтра в таблице Users rating
  status: pass

- summary:
    Проверка возможности смены языка на русский и английский в Task
  status: fail

- summary:
    Проверка возможности общения с пользователями в чате
  status: pass

- summary:
    Проверка возможности создания нового турнира
  status: pass

- summary:
    Проверка возможности отмены турнира
  status: pass

- summary:
    Проверка выхода из Codebattle
  status: pass

- summary:
    Проверка возможности просмотра завершенной игры
  status: pass

- summary:
    Проверка создания игры с ботом
  status: pass

- summary:
    Проверка возможности наблюдать за игрой
  status: pass
