---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в решении задач на скорость
  - Пользователи должны видеть написание кода друг у друга
  - Пользователи должны иметь возможность начисления очков для рейтинга
  - Пользователь должен иметь возможность проведения игры с ботом
  - Пользователи должны иметь возможность проведения игры с другом по ссылке
  - Пользователь должен иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбора игры по уровню сложности
  - Пользователь должен иметь возможность видеть задачи на русском и английском языках
  - Пользователи не принимающие участие в игре должны иметь возможность следить за ходом игры
  - Зарегистрированные пользователи должны иметь возможность общаться в чате
  - Пользователи должны иметь доступ к завершенным играм в записи
  - Пользователи должны иметь возможность получать очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Редактор для ввода кода выглядит как проигрыватель
implicit:
  - Возможность регистрации
  - Возможность авторизации
  - Проект с открытым исходным кодом
  - Игра проходит в реальном времени
