---
functional
  - Возможность двум игрокам соревноваться друг с другом в решении задач на скорость
  - Возможность видеть написание кода друг у друга
  - Возможность начисления очков для рейтинга
  - Возможность проведения игры с ботом
  - Возможность проведения игры с другом по ссылке
  - Возможность менять язык программирования во время решения
  - Выбор игры по уровню сложности
  - Задачи даны на двух языках русском и английском
  - Пользователи не принимающие участие в игре могут следить за ходом игры
  - Зарегистрированные пользователи могут общаться в чате
  - Завершенная игра доступна в записи
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Редактор для ввода кода выглядит как проигрыватель
implicit
  - Возможность регистрации
  - Возможность авторизации
  - Проект с открытым исходным кодом
  - Игра проходит в реальном времени
